//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyScreens.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingContractTable
    {
        public int ID { get; set; }
        public string Department { get; set; }
        public string Customer { get; set; }
        public string ContractTitles { get; set; }
        public string Notes { get; set; }
        public string Recommendations { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
